language: node_js
node_js:
  - "9"
dist: trusty
sudo: required

branches:
  only:
  - master

before_script:
  - npm install -g @angular/cli
  - npm install -g @angular-devkit/build-angular

script:
- cd personal-website
- npm link
- ng lint
- ng build --prod --output-path ../docs

deploy:
  provider: pages
  local-dir: /docs
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  keep-history: true
  on:
    branch: master