language: node_js
node_js:
  - "9"
dist: trusty
sudo: required

branches:
  only:
  - master

addons:
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable

before_script:
  - npm install -g @angular/cli
  - npm install -g @angular-devkit/build-angular

cache:
  directories:
     - ./personal-website/node_modules

script:
- cd personal-website
- npm link
- ng lint
- ng test --watch=false --progress=false --browsers=ChromeHeadlessCI
- ng e2e --protractor-config=./e2e/protractor-ci.conf.js
- ng build --prod --output-path ../docs
- cd ../docs && echo jamiefinnigan.dev > CNAME && cp index.html 404.html

deploy:
  provider: pages
  target-branch: master
  skip-cleanup: true
  github-token: $GITHUB_API_KEY
  keep-history: true
  on:
    branch: master